#!/usr/bin/env python3
"""Self-check for scripts/port-agents.py (issue #20): Codex [agents.<key>]
emission, hand-authored-agent import from Codex config.toml AND opencode
agent files, and round-trip idempotence both directions on a scratch
config.toml. Run: python3 test_port_agents.py"""
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent


def _write(p, text):
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(text)


def _scratch():
    scratch = Path(tempfile.mkdtemp(prefix="agent-home-agents-"))
    home, store = scratch / "home", scratch / "store"
    home.mkdir()
    (store / "agents").mkdir(parents=True)
    return scratch, home, store


def _run(home, store, *args):
    env = dict(os.environ, HOME=str(home), AGENT_HOME=str(store))
    return subprocess.run([sys.executable, str(REPO / "scripts/port-agents.py"), *args],
                           cwd=REPO, env=env, capture_output=True, text=True)


def test_codex_emission_and_check_clean():
    """A store agent generates a marked [agents.<name>] block in every
    codex_home's config.toml, and --check is clean right after."""
    scratch, home, store = _scratch()
    _write(store / "agents/reviewer.md",
           "---\nname: reviewer\ndescription: reviews diffs\n---\n\nReview the diff for bugs.\n")
    r = _run(home, store, "")
    assert r.returncode == 0, r.stderr
    toml_text = (home / ".codex/config.toml").read_text()
    assert "[agents.reviewer]" in toml_text
    assert 'description = "reviews diffs"' in toml_text
    assert "developer_instructions" in toml_text
    assert "model = " not in toml_text and "sandbox_mode = " not in toml_text  # unverified fields never emitted

    rc = _run(home, store, "--check")
    assert rc.returncode == 0, rc.stdout + rc.stderr
    shutil.rmtree(scratch)


def test_codex_hand_authored_agent_imports_and_round_trips():
    """A role authored directly as [agents.<key>] in Codex's config.toml (no
    MARKER) imports into the store, then generates back out marked — matching
    #20's acceptance line. Running again afterwards is a no-op (idempotent)."""
    scratch, home, store = _scratch()
    _write(home / ".codex/config.toml",
           'forced_login_method = "chatgpt"\n\n'
           "[agents.triager]\n"
           'name = "triager"\n'
           'description = "triages incoming issues"\n'
           'developer_instructions = "Sort issues by severity."\n')

    r1 = _run(home, store, "")
    assert r1.returncode == 0, r1.stderr
    assert "imported codex agent 'triager'" in r1.stdout
    imported_md = (store / "agents/triager.md").read_text()
    assert "description: triages incoming issues" in imported_md
    assert "Sort issues by severity." in imported_md

    toml_after = (home / ".codex/config.toml").read_text()
    assert toml_after.count("[agents.triager]") == 1  # imported role re-emitted marked, not duplicated
    assert "# generated by agent-home" in toml_after

    r2 = _run(home, store, "")
    assert r2.returncode == 0, r2.stderr
    assert "imported codex agent" not in r2.stdout  # already in the store — no re-import
    assert (home / ".codex/config.toml").read_text() == toml_after  # idempotent

    rc = _run(home, store, "--check")
    assert rc.returncode == 0, rc.stdout + rc.stderr
    shutil.rmtree(scratch)


def test_opencode_hand_authored_agent_imports():
    """A non-MARKER file in ~/.config/opencode/agent/ imports into the store."""
    scratch, home, store = _scratch()
    _write(home / ".config/opencode/agent/planner.md",
           "---\ndescription: plans work\nmode: subagent\n---\n\nBreak work into steps.\n")

    r = _run(home, store, "")
    assert r.returncode == 0, r.stderr
    assert "imported opencode agent 'planner'" in r.stdout
    imported_md = (store / "agents/planner.md").read_text()
    assert "description: plans work" in imported_md
    assert "Break work into steps." in imported_md
    shutil.rmtree(scratch)


def test_plugin_shipped_agents_are_wired_in():
    """all_source_agents() unions in sync.enabled_plugin_agent_dirs() — a
    plugin-shipped agent reaches both opencode and Codex, store wins on a
    name collision."""
    scratch, home, store = _scratch()
    _write(store / "plugins/demo/agents/helper.md",
           "---\nname: helper\ndescription: from the plugin\n---\n\nHelp.\n")
    _write(store / "plugins/demo/plugin.json", "{}")
    _write(store / "plugins/enabled.json", '{"demo": true}')
    r = _run(home, store, "")
    assert r.returncode == 0, r.stderr
    assert (home / ".config/opencode/agent/helper.md").exists()
    assert "[agents.helper]" in (home / ".codex/config.toml").read_text()
    shutil.rmtree(scratch)


if __name__ == "__main__":
    test_codex_emission_and_check_clean()
    test_codex_hand_authored_agent_imports_and_round_trips()
    test_opencode_hand_authored_agent_imports()
    test_plugin_shipped_agents_are_wired_in()
    print("port-agents self-check: PASS")
