#!/usr/bin/env python3
"""Translate Claude-format subagents (~/.agent-home/agents/*.md) into opencode's
agent format (~/.config/opencode/agent/*.md). The mapping is mechanical:
description carries over, `tools:` becomes opencode's boolean map, `model:`
resolves through ~/.agent-home/models.json aliases (dropped if unmapped —
opencode then uses its default model).

Idempotent: generated files carry a marker comment and are regenerated each
run; a same-named file WITHOUT the marker is yours and is never touched.
Orphans (source agent deleted) are removed.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import sync

MARKER = "# generated by agent-home"
OC_DIR = Path.home() / ".config/opencode/agent"
# Claude tool name -> opencode tool name (unknown tools are dropped)
TOOLS = {"Read": "read", "Grep": "grep", "Glob": "glob", "Bash": "bash",
         "Edit": "edit", "Write": "write", "WebFetch": "webfetch",
         "WebSearch": "websearch", "TodoWrite": "todowrite"}


def parse_frontmatter(text):
    """(fields, body) from a `---` frontmatter block; single-line values only."""
    if not text.startswith("---"):
        return {}, text
    head, _, body = text[3:].partition("\n---")
    fields = {}
    for line in head.splitlines():
        k, sep, v = line.partition(":")
        if sep and k.strip() and not k.startswith(" "):
            fields[k.strip()] = v.strip()
    return fields, body.lstrip("\n")


def model_alias(name):
    try:
        aliases = json.load(open(sync.CANON / "models.json")).get("aliases", {})
        return aliases.get(name, {}).get("opencode")
    except (OSError, json.JSONDecodeError):
        return None


def _build(src):
    """source agent -> (dest path, intended file content). Shared by main()
    (which writes it) and check() (which diffs it against the live file)."""
    fields, body = parse_frontmatter(src.read_text())
    dest = OC_DIR / src.name
    lines = ["---",
             f"{MARKER} from {src} — edit the source, then `make agents`",
             f"description: {json.dumps(fields.get('description', src.stem))}",
             "mode: subagent"]
    model = model_alias(fields.get("model", ""))
    if model:
        lines.append(f"model: {model}")
    if fields.get("tools"):
        allowed = {TOOLS[t.strip()] for t in fields["tools"].split(",") if t.strip() in TOOLS}
        lines.append("tools:")
        lines += [f"  {t}: {str(t in allowed).lower()}" for t in sorted(set(TOOLS.values()))]
    lines += ["---", "", body]
    return dest, "\n".join(lines)


def main():
    src_dir = sync.CANON / "agents"
    OC_DIR.mkdir(parents=True, exist_ok=True)
    generated = set()
    for src in sorted(src_dir.glob("*.md")):
        dest, content = _build(src)
        if dest.exists() and MARKER not in dest.read_text():
            print(f"  skip {src.name}: hand-written opencode agent exists", file=sys.stderr)
            continue
        dest.write_text(content)
        generated.add(dest.name)
        print(f"  {src.stem} -> {dest}")
    # remove generated agents whose source is gone
    for f in OC_DIR.glob("*.md"):
        if f.name not in generated and MARKER in f.read_text():
            f.unlink()
            print(f"  removed orphan {f.name}")
    print(f"opencode agents: {len(generated)} generated")


def check():
    """--check: diff generated agents against their sources without writing
    anything, plus orphans (source deleted, generated file still present).
    Returns True if no drift."""
    src_dir = sync.CANON / "agents"
    live_names = {s.name for s in src_dir.glob("*.md")}
    drift = []
    for src in sorted(src_dir.glob("*.md")):
        dest, content = _build(src)
        if dest.exists() and MARKER not in dest.read_text():
            continue  # hand-written, not ours to check
        if not dest.exists() or dest.read_text() != content:
            drift.append(dest.name)
    if OC_DIR.exists():
        for f in OC_DIR.glob("*.md"):
            if f.name not in live_names and MARKER in f.read_text():
                drift.append(f"{f.name} (orphan)")
    if drift:
        print(f"port-agents --check: drift in {drift} — run: make agents")
    return not drift


if __name__ == "__main__":
    if "--check" in sys.argv:
        sys.exit(0 if check() else 1)
    else:
        main()
